image: node:latest

# This folder is cached between builds
# https://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
    - .cache/
    - public/



deploy-site:
  script:
      - whoami    
      - ls -alh /
      - ls -alh /etc
      - cat /etc/debian_version
      - ls -al /root
      - cat /root/.ssh/known_hosts
      - scp -Cpr ./public root@10.163.254.215:/var/www/static/catlike-gatsby