image: node:latest



deploy-site:
  script:
      - whoami    
      - ls -alh /
      - cat /etc/debian_version
      - ls -al /ssh-cfg
      - ls -al /root
      - mkdir /root/.ssh/
      - ls -al /root
      - cp /ssh-cfg/* /root/.ssh/
      - cat /root/.ssh/known_hosts
      - scp -Cpr ./public root@10.163.254.215:/var/www/static/catlike-gatsby
      